<a href="https://colab.research.google.com/github/joony0512/archive/blob/main/optimization/1%EC%B0%A8%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1 
_sum = 0
for i in range(1,7):
    _sum += 1/i
print(_sum)


2.4499999999999997


In [ ]:
#2 
import math

a= lambda x, y, j, k : math.sqrt((x + y )*(j + k))
a(4,3,2,5)


7.0

In [ ]:
#3
import math

a = lambda x, y, j, k : math.pow(((x + y)/(j + k)),2)
a(1,2,4,5)


0.1111111111111111

In [ ]:
#4
import math

a= lambda x,y : (3* math.pow(x,2) + 2* math.pow(y,3))/((x+y)*(x-y))

a = a(15, 4)
a

3.8421052631578947

In [ ]:
#5
import numpy as np
x = np.array([2,3,5,7,9])

x2 = np.array(x)**2
print(x2)

[ 4  9 25 49 81]


In [ ]:
#6
import numpy as np
x = np.array([2,3,5,7,9])
x2 = (np.array(x)**2)
_sum = 0
for i in x2:
    _sum += i
    
print(_sum)

168


In [ ]:
#7
import numpy as np
x = np.array([2,3,5,7,9])

_max = max(x)
_min = min(x)
_avg = sum(x)/len(x)

print(_max)
print(_min)
print(_avg)

9
2
5.2


In [ ]:
#8
import numpy
x = np.array([2,3,5,7,9])
x_up = []
for i in x:
    if i > 5 :
        x_up.append(i) 
x_up = np.array(x_up)
print(x_up)


[7 9]


In [ ]:
#9
import math
x = np.array([2,3,5,7,9])
x_ss= 0
for i in x :
    x_ss += i**2
x_len = math.sqrt(x_ss)
print(x_len)

12.96148139681572


In [ ]:
#10
import numpy as np
x = np.matrix([2,3,5,7,9])
xT = np.transpose(x)
print(x@xT)
print(xT@x)


[[168]]
[[ 4  6 10 14 18]
 [ 6  9 15 21 27]
 [10 15 25 35 45]
 [14 21 35 49 63]
 [18 27 45 63 81]]
